# Generated by Django 5.2.12 on 2026-04-01 08:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('blood_pressure', 'Кровяное давление'), ('heart_rate', 'Сердечный ритм'), ('steps', 'Шаги'), ('weight', 'Вес'), ('temperature', 'Температура'), ('mood', 'Самочувствие'), ('water', 'Вода'), ('sleep', 'Сон'), ('blood_sugar', 'Сахар в крови'), ('oxygen', 'Кислород (SpO2)')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(choices=[('daily', 'В день'), ('weekly', 'В неделю')], default='daily', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Цель здоровья',
                'verbose_name_plural': 'Цели здоровья',
                'unique_together': {('subject', 'metric_type', 'period')},
            },
        ),
        migrations.CreateModel(
            name='MetricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('blood_pressure', 'Кровяное давление'), ('heart_rate', 'Сердечный ритм'), ('steps', 'Шаги'), ('weight', 'Вес'), ('temperature', 'Температура'), ('mood', 'Самочувствие'), ('water', 'Вода'), ('sleep', 'Сон'), ('blood_sugar', 'Сахар в крови'), ('oxygen', 'Кислород (SpO2)')], max_length=20)),
                ('value_json', models.JSONField()),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('magic_link', 'Magic Link'), ('auto', 'Автоматически')], default='manual', max_length=15)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись метрики',
                'verbose_name_plural': 'Записи метрик',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['subject', 'metric_type', '-recorded_at'], name='health_metr_subject_95ad72_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThresholdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('blood_pressure', 'Кровяное давление'), ('heart_rate', 'Сердечный ритм'), ('steps', 'Шаги'), ('weight', 'Вес'), ('temperature', 'Температура'), ('mood', 'Самочувствие'), ('water', 'Вода'), ('sleep', 'Сон'), ('blood_sugar', 'Сахар в крови'), ('oxygen', 'Кислород (SpO2)')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Порог метрики',
                'verbose_name_plural': 'Пороги метрик',
                'unique_together': {('subject', 'metric_type')},
            },
        ),
    ]
