# Generated by Django 5.2.12 on 2026-04-01 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('invite_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Семейная группа',
                'verbose_name_plural': 'Семейные группы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relation', models.CharField(choices=[('mother', 'Мама'), ('father', 'Папа'), ('grandmother', 'Бабушка'), ('grandfather', 'Дедушка'), ('spouse', 'Супруг(а)'), ('child', 'Ребёнок'), ('sibling', 'Брат/Сестра'), ('other', 'Другой')], default='other', max_length=20)),
                ('can_view_metrics', models.BooleanField(default=True)),
                ('can_view_location', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='family.familygroup')),
                ('magic_link', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='accounts.magiclink')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observing', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='being_observed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник семьи',
                'verbose_name_plural': 'Участники семьи',
                'unique_together': {('group', 'observer', 'subject_email')},
            },
        ),
        migrations.CreateModel(
            name='FamilyInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='family.familygroup')),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='family.familymembership')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
            },
        ),
    ]
