# Generated by Django 5.2.12 on 2026-04-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=5)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('temperature_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feels_like_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity_pct', models.PositiveSmallIntegerField()),
                ('wind_speed_ms', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure_hpa', models.PositiveIntegerField(default=1013)),
                ('weather_main', models.CharField(max_length=50)),
                ('weather_desc', models.CharField(max_length=200)),
                ('weather_icon', models.CharField(blank=True, max_length=10)),
                ('uv_index', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('visibility_m', models.PositiveIntegerField(blank=True, null=True)),
                ('aqi', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Хорошо'), (2, 'Удовлетворительно'), (3, 'Умеренно'), (4, 'Плохо'), (5, 'Очень плохо')], null=True)),
                ('pm25', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('pm10', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('no2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_dangerous_air', models.BooleanField(default=False)),
                ('is_extreme_heat', models.BooleanField(default=False)),
                ('is_extreme_cold', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Погодный кеш',
                'verbose_name_plural': 'Погодный кеш',
                'ordering': ['-fetched_at'],
                'get_latest_by': 'fetched_at',
            },
        ),
    ]
