# Generated by Django 5.2.12 on 2026-04-01 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('active_longevity', 'Центр активного долголетия'), ('clinic', 'Поликлиника'), ('pharmacy', 'Аптека'), ('park', 'Парк'), ('social_club', 'Клуб / кружок'), ('rehab', 'Реабилитация'), ('social_service', 'Социальные услуги')], max_length=20)),
                ('city', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('working_hours', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Полезное место',
                'verbose_name_plural': 'Полезные места',
                'ordering': ['city', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LocationSharingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_with_family', models.BooleanField(default=True)),
                ('allow_manual_updates', models.BooleanField(default=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('home_address', models.CharField(blank=True, max_length=220)),
                ('emergency_contact_notes', models.TextField(blank=True)),
                ('last_shared_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_sharing_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки геолокации',
                'verbose_name_plural': 'Настройки геолокации',
            },
        ),
        migrations.CreateModel(
            name='WearableDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('xiaomi', 'Xiaomi / Mi Band'), ('huawei', 'Huawei'), ('samsung', 'Samsung'), ('apple', 'Apple Health'), ('google_fit', 'Google Fit'), ('fitbit', 'Fitbit'), ('other', 'Другое')], max_length=20)),
                ('nickname', models.CharField(max_length=80)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фитнес-браслет',
                'verbose_name_plural': 'Фитнес-браслеты',
                'ordering': ['-is_active', 'nickname'],
            },
        ),
        migrations.CreateModel(
            name='DailyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('medication', 'Лекарства'), ('doctor_visit', 'Врач'), ('walk', 'Прогулка'), ('exercise', 'Упражнения'), ('health_check', 'Проверка здоровья'), ('meal', 'Питание'), ('social', 'Общение'), ('task', 'Дело')], default='task', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий')], default='normal', max_length=10)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('via_voice', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_daily_plan_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_daily_plan_items', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plan_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача дня',
                'verbose_name_plural': 'Задачи дня',
                'ordering': ['scheduled_date', 'scheduled_time', 'created_at'],
                'indexes': [models.Index(fields=['subject', 'scheduled_date', 'is_completed'], name='care_dailyp_subject_81e480_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('phone', 'Телефон'), ('wearable', 'Браслет')], default='manual', max_length=12)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_location_pings', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Точка геолокации',
                'verbose_name_plural': 'Точки геолокации',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['subject', '-captured_at'], name='care_locati_subject_447367_idx')],
            },
        ),
        migrations.CreateModel(
            name='WearableDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField(db_index=True)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('average_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('calories_kcal', models.PositiveIntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_wearable_summaries', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='care.wearabledevice')),
            ],
            options={
                'verbose_name': 'Сводка браслета',
                'verbose_name_plural': 'Сводки браслета',
                'ordering': ['-summary_date', '-synced_at'],
                'unique_together': {('device', 'summary_date')},
            },
        ),
    ]
