# Generated by Django 5.2.12 on 2026-04-01 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplanitem',
            name='doctor_address',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='dailyplanitem',
            name='doctor_specialty',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='dailyplanitem',
            name='medicine_dosage',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='dailyplanitem',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='dailyplanitem',
            name='recurrence_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dailyplanitem',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyplanitem',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_occurrences', to='care.dailyplanitem'),
        ),
        migrations.AddField(
            model_name='dailyplanitem',
            name='recurrence_type',
            field=models.CharField(choices=[('once', 'Один раз'), ('daily', 'Каждый день'), ('weekly', 'По дням недели'), ('monthly', 'Каждый месяц')], default='once', max_length=10),
        ),
        migrations.AddField(
            model_name='dailyplanitem',
            name='water_amount_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationping',
            name='is_emergency',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='locationsharingsettings',
            name='home_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='locationsharingsettings',
            name='home_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='locationsharingsettings',
            name='last_absence_alert_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationsharingsettings',
            name='max_absence_hours',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='locationsharingsettings',
            name='tracking_consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationsharingsettings',
            name='tracking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wearabledailysummary',
            name='active_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wearabledailysummary',
            name='deep_sleep_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='wearabledailysummary',
            name='heart_rate_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wearabledailysummary',
            name='heart_rate_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wearabledailysummary',
            name='light_sleep_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='wearabledailysummary',
            name='sleep_quality',
            field=models.CharField(blank=True, choices=[('poor', 'Плохой'), ('fair', 'Удовлетворительный'), ('good', 'Хороший'), ('excellent', 'Отличный')], max_length=10),
        ),
        migrations.AlterField(
            model_name='communityplace',
            name='category',
            field=models.CharField(choices=[('active_longevity', 'Центр активного долголетия'), ('clinic', 'Поликлиника'), ('pharmacy', 'Аптека'), ('park', 'Парк'), ('grocery', 'Продуктовые магазины'), ('social_club', 'Клуб / кружок'), ('rehab', 'Реабилитация'), ('social_service', 'Социальные услуги'), ('transport', 'Остановки транспорта')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyplanitem',
            name='category',
            field=models.CharField(choices=[('medication', 'Лекарства'), ('doctor_visit', 'Врач'), ('walk', 'Прогулка'), ('exercise', 'Упражнения'), ('health_check', 'Проверка здоровья'), ('meal', 'Питание'), ('water', 'Вода'), ('social', 'Общение'), ('shopping', 'Покупки'), ('task', 'Дело')], default='task', max_length=20),
        ),
        migrations.CreateModel(
            name='SafeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_meters', models.PositiveIntegerField(default=300)),
                ('is_home', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Безопасная зона',
                'verbose_name_plural': 'Безопасные зоны',
                'ordering': ['-is_home', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FavoritePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='care.communityplace')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное место',
                'verbose_name_plural': 'Избранные места',
                'ordering': ['-created_at'],
                'unique_together': {('subject', 'place')},
            },
        ),
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_before_minutes', models.PositiveIntegerField(default=60)),
                ('sent', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='care.dailyplanitem')),
            ],
            options={
                'verbose_name': 'Напоминание по задаче',
                'verbose_name_plural': 'Напоминания по задачам',
                'ordering': ['remind_before_minutes'],
                'unique_together': {('task', 'remind_before_minutes')},
            },
        ),
    ]
