# Generated by Django 5.2.12 on 2026-04-01 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('challenge_type', models.CharField(choices=[('steps_total', 'Сумма шагов за период'), ('steps_daily', 'Ежедневные шаги'), ('bp_streak', 'Дни с нормальным давлением подряд'), ('water_daily', 'Ежедневная норма воды'), ('mood_streak', 'Дни с хорошим самочувствием')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='family.familygroup')),
            ],
            options={
                'verbose_name': 'Челлендж',
                'verbose_name_plural': 'Челленджи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('streak_days', models.PositiveSmallIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['-current_value'],
                'unique_together': {('challenge', 'user')},
            },
        ),
    ]
