# Generated by Django 5.2.12 on 2026-04-01 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField()),
                ('response_text', models.TextField()),
                ('action_type', models.CharField(choices=[('answer', 'Ответ'), ('plan_query', 'Запрос плана'), ('plan_complete', 'Отметка плана'), ('medication_log', 'Лекарство'), ('doctor_log', 'Визит к врачу'), ('metric_log', 'Лог метрики'), ('unsupported', 'Не распознано')], default='answer', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_command_subject_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_command_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Голосовая команда',
                'verbose_name_plural': 'Голосовые команды',
                'ordering': ['-created_at'],
            },
        ),
    ]
