# Generated by Django 5.2.12 on 2026-04-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_voicecommandlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicecommandlog',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voicecommandlog',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='voicecommandlog',
            name='is_system_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voicecommandlog',
            name='requires_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voicecommandlog',
            name='action_type',
            field=models.CharField(choices=[('answer', 'Ответ'), ('plan_query', 'Запрос плана'), ('plan_complete', 'Отметка плана'), ('medication_log', 'Лекарство'), ('doctor_log', 'Визит к врачу'), ('metric_log', 'Лог метрики'), ('reminder', 'Напоминание'), ('cancelled', 'Отменено'), ('unsupported', 'Не распознано')], default='answer', max_length=20),
        ),
    ]
